name: sandbox_flutter
description: A new Flutter project.
publish_to: 'none'

# Version number: MMAAPP (major - M, minor - A, patch - P)
version: 0.0.1+000001

# Flutter version: 3.16.2
environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Style
  swipeable_page_route: ^0.4.0
  animated_size_and_fade: ^3.0.1

  # State
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # HTTP & Web view
  dio: ^5.4.0
  http: any
  webview_flutter: ^4.4.2
  connectivity_plus: ^5.0.2

  # Firebase
  firebase_core: ^2.24.1
  firebase_auth: ^4.15.1
  cloud_firestore: ^4.13.4
  firebase_analytics: ^10.7.3
  firebase_crashlytics: ^3.4.7

  # Global - Services
  get_it: ^7.6.4
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1

  # Other
  dartz: ^0.10.1
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_localization: ^0.1.14

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800