name: sandbox_flutter
description: A new Flutter project.
publish_to: 'none'

# Version number: MMAAPP (major - M, minor - A, patch - P)
version: 0.0.1+000001

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Style
  swipeable_page_route: ^0.3.0

  # State
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.18

  # HTTP & Web view
  dio: ^5.0.2
  webview_flutter: ^4.0.6
  connectivity_plus: ^3.0.3

  # Firebase

  # Global - Services
  get_it: ^7.2.0
  package_info_plus: ^3.0.3

  # Other
  dartz: ^0.10.1
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_localization: ^0.1.10

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800