name: sandbox_flutter
description: "A new Flutter project."
publish_to: 'none'

# Flutter version: 3.24.3
# Build version format: MM.AA.PP (major - M, minor - A, patch - P)
# Build name format: +MMAAPPVVV (major - M, minor - A, patch - P, version - V)
version: 0.0.1+000001001

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Style
  swipeable_page_route: ^0.4.4
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3

  # Firebase
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3

  # Supabase
  supabase_flutter: ^2.7.0

  # State
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

  # HTTP & Web view & Network connection
  http: any
  web: any
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

  # Global services
  get_it: ^8.0.0
  package_info_plus: ^8.0.2
  device_info_plus: ^11.0.0
  easy_localization: ^3.0.7
  permission_handler: ^11.3.1
  go_router: ^14.2.8
  flutter_local_notifications: ^17.2.2
  local_auth: ^2.3.0

  # Other
  dartz: ^0.10.1
  email_validator: ^3.0.0
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700